#!/bin/bash
set -e
useragent="https://github.com/satanicantichrist/Paper-Tool (contact@satanicantichrist.cz)"
basecommand="papertool"

printVersion(){
    if ! [ -e version.json ]
        then
            echo "No server installation found, run \"$basecommand install <game-version>\" to install it."
            exit 1
        fi

    echo "Installed Minecraft version: $(jq -r ".minecraft" ./version.json)"
    echo "Installed Paper build: $(jq -r ".paper" ./version.json)"
}

acceptEula(){
    echo "eula=true" > eula.txt
    echo "Accepted Eula"
}

defaultRun(){
    echo "Starting server..."
    java -jar server.jar --nogui
}

updateExisting(){
	if ! [ -e version.json ]
	then
		echo "No server installation found, run \"$basecommand install <game-version>\" to install it."
		exit 1
	fi
	mcversion=$(jq -r ".minecraft" ./version.json)
	prversion=$(jq ".paper" ./version.json)
	echo "Current minecrat version $mcversion"
	echo "Current Paper version $prversion"

	echo "Fetching newest Paper version..."
	paperdata=$(curl -s -A "$useragent" https://api.papermc.io/v2/projects/paper/versions/$mcversion/builds)
	nprversion=$(echo $paperdata | jq "[.builds.[].build] | max")
	if [[ $prversion -ge $nprversion ]]
	then
		echo "You already have the newest version of Paper."
		exit 0
	fi

	echo "New version of Paper found ($nprversion), downloading..."
	curl -A "$useragent" --progress-bar https://api.papermc.io/v2/projects/paper/versions/$mcversion/builds/$nprversion/downloads/paper-$mcversion-$nprversion.jar -o ./server.jar
	echo "{\"minecraft\": \""$mcversion"\",\"paper\": "$nprversion"}" > version.json

}

downloadNew(){
	mcversion=$1
	paperversion=$2
	echo "Fetching newest Paper version for Minecraft $mcversion..."
	paperdata=$(curl -s -A "$useragent" https://api.papermc.io/v2/projects/paper/versions/$mcversion/builds)
	if [[ $paperversion == "" ]]
		then
			nprversion=$(echo $paperdata | jq "[.builds.[].build] | max")
    else
		nprversion=$paperversion
    fi

	echo "Downloading Paper ($nprversion)..."
	curl -A "$useragent" --progress-bar https://api.papermc.io/v2/projects/paper/versions/$mcversion/builds/$nprversion/downloads/paper-$mcversion-$nprversion.jar -o ./server.jar
	echo "{\"minecraft\": \""$mcversion"\",\"paper\": "$nprversion"}" > version.json

}

installHelp(){
    echo "To install a new server run \"$basecommand install <game-version>\""
    echo "Or with specific build of paper run \"$basecommand install <game-version> <paper-build-id>\""
}

listHelp(){
	echo "To list available Minecraft version run \"$basecommand ls mc\""
	echo "To list available Paper versions run \"$basecommand ls paper <game-version>\""
}

infoHelp(){
    echo "To see currently installed version, run \"$basecommand info\""
}

globalHelp(){
    listHelp
    echo ""
    installHelp
    echo ""
    infoHelp
}

listMc(){
	echo "Available Minecraft versions:"
	curl -s -A "$useragent" https://api.papermc.io/v2/projects/paper/ | jq -r ".versions.[]" | while read -r mc; do echo $mc; done
}

listPaper(){
	echo "Available Paper builds for Minecraft $1"
	curl -s -A "$useragent" https://api.papermc.io/v2/projects/paper/versions/$1/builds | jq -r ".builds.[]" | jq -r ".build" |  while read -r build; do echo $build; done
}

if [[ $1 == "run" ]]
    then
        if [[ $2 == "accept-eula" ]]
            then
                acceptEula
            fi
        defaultRun
        exit 0
    fi

if [[ $1 == "accept-eula" ]]
    then
        acceptEula
        exit 0
    fi

if [[ $1 == "info" ]]
    then
        printVersion
        exit 0
    fi

if [[ $1 == "ls" ]]
	then
		if [[ $2 == "" ]]
			then
			    listHelp
				exit 0
			fi

			if [[ $2 == "mc" ]]
			 then
		        listMc
				exit 0
			fi

		if [[ $2 == paper ]] && [[ $3 == "" ]]
		  then
				listHelp
				exit 1
			fi

		if [[ $2 == "paper" ]] && [[ $3 != "" ]]
			then
			    listPaper $3
				exit 0
			fi
		exit 0
	fi


if [[ $1 == "update" ]]
    then
        updateExisting
	exit 0
fi

if [[ $1 == "install" ]]
    then
        if [[ $2 == "" ]]
            then
                installHelp
                exit 1
            else
            downloadNew $2 $3
            exit 0
        fi
	exit 0
fi

if [[ $1 == "help" ]]
    then
        globalHelp
        exit 0
fi

if [[ $1 == "" ]]
    then
        globalHelp
        exit 0
fi
